# Generated by Django 2.2 on 2020-10-11 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(default='', max_length=150)),
                ('publisher', models.CharField(default='', max_length=60)),
                ('file', models.FileField(upload_to='books/%Y/%m/%d/')),
                ('cover', models.ImageField(default='default_cover.jpg', upload_to='books_cover_page/%Y/%m/%d/')),
                ('edition', models.CharField(max_length=15)),
                ('pages', models.IntegerField(verbose_name='Number of Pages')),
                ('language', models.CharField(max_length=20)),
                ('pub_year', models.DateField(verbose_name='Year Published')),
                ('summary', models.TextField(verbose_name='Book Summary')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category'),
        ),
    ]
